Package.swift: Update macOS deployment target to v11
when running for macOS, as depended on through stream-chat-swiftui, the following error comes up

```
error: the library 'StreamChatTestMockServer' requires macos 10.15, but depends on the product 'StreamChatTestHelpers' which requires macos 11.0; consider changing the library 'StreamChatTestMockServer' to require macos 11.0 or later, or the product 'StreamChatTestHelpers' to require macos 10.15 or earlier.
error: the library 'StreamChatTestTools' requires macos 10.15, but depends on the product 'StreamChatTestHelpers' which requires macos 11.0; consider changing the library 'StreamChatTestTools' to require macos 11.0 or later, or the product 'StreamChatTestHelpers' to require macos 10.15 or earlier.
```

this should make it possible for the dependencies to resolve on macOS